chcon u:object_r:same_process_hal_file:s0 /vendor/lib/libadreno_app_profiles.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib/libadreno_utils.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib/libdmabufheap.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib/libgsl.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib/libllvm-glnext.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib/libllvm-qcom.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib/libllvm-qgl.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib/libOpenCL.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib/egl/eglSubDriverAndroid.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib/egl/libEGL_adreno.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib/egl/libGLESv1_CM_adreno.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib/egl/libGLESv2_adreno.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib/egl/libq3dtools_adreno.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib/egl/libq3dtools_esx.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib/egl/libVkLayer_ADRENO_qprofiler.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib/hw/vulkan.adreno.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib64/libadreno_app_profiles.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib64/libadreno_utils.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib64/libdmabufheap.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib64/libgsl.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib64/libllvm-glnext.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib64/libllvm-qcom.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib64/libllvm-qgl.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib64/libOpenCL.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib64/egl/eglSubDriverAndroid.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib64/egl/libEGL_adreno.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib64/egl/libGLESv1_CM_adreno.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib64/egl/libGLESv2_adreno.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib64/egl/libq3dtools_adreno.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib64/egl/libq3dtools_esx.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib64/egl/libVkLayer_ADRENO_qprofiler.so 
chcon u:object_r:same_process_hal_file:s0 /vendor/lib64/hw/vulkan.adreno.so 
